CREATE TABLE users(
  id INTEGER PRIMARY KEY AUTOINCREMENT,

  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255),
  
  user_type VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP

  UNIQUE(email)
);
